apiVersion: core.choreo.dev/v1alpha1
kind: Component
metadata:
  name: nck-dev-vps
  displayName: NCK DEV VPS
  description: VPS Panel with Flutterwave payments & GitHub backup
  version: v1.0
  annotations:
    choreo.dev/display-name: NCK DEV VPS
    choreo.dev/component-type: service
spec:
  type: service
  build:
    buildPreset: python
    languageVersion: 3.11.x
    commands:
      build: pip install -r requirements.txt
      start: gunicorn --bind :8080 app:app
  endpoints:
    - name: default-endpoint
      port: 8080
      type: REST
      context: /
      networkVisibility: Public
      security: {}
